spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
